# Generated by Django 5.2 on 2025-06-25 13:23

import blog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post (10-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=250, unique_for_date='publish_date')),
                ('summary', models.TextField(help_text='Brief summary of the blog post', max_length=500)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('AR', 'Archived')], default='DF', help_text='Current publication status', max_length=2)),
                ('publish_date', models.DateTimeField(blank=True, help_text='Date when the blog was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the section (5-100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(blank=True, help_text='Optional description of the section (max 500 characters)', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section', null=True, upload_to=blog.models.section_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('code_snippet', models.TextField(blank=True, help_text='Code snippet to display with syntax highlighting')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash'), ('text', 'Generic Text')], default='python', help_text='Programming language for syntax highlighting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Sections',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the section within the blog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='blog.blog')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='blog.section')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('blog', 'section')},
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='sections',
            field=models.ManyToManyField(help_text='Sections contained in this blog post', related_name='blogs', through='blog.BlogSection', to='blog.section'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing the blog post', related_name='blogs', to='blog.tag'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-publish_date'], name='blog_blog_publish_d8aefd_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status'], name='blog_blog_status_e6780b_idx'),
        ),
    ]
